# -*- coding: utf-8 -*-
"""Another copy of Employee data stat and python project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZM7phzGrm1H9wHyDWvZR3oqfgXZoLme3
"""

# EMPLOYEE DATA SET


# Load all the data frames

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# PART 1 SCANNING THE DATA
# Read in the 'Emplyee dataset' as a pandas Dataframe

data = pd.read_csv('/Employee Dataset stats and python.csv')
data.head()
# Take brief look at the data
# Take dimenions of the Dataframe

# data.shape
# data.index
# data.columns

# basic information about the data
# data.info()

# PART2 ANALYSE DATA USING MATPLOTLIB
# 1.Create a scatter plot of "Age"and "Employee Salary" features

# plt.figure(figsize= (10,5))
# sns.scatterplot(data=data, x = 'age', y = 'salary', color ='blue',edgecolor ='green', alpha = 0.5)
# plt.title("Scatterplot of Employee Age v/s Employee Salary")
# plt.xlabel('Employee Age')
# plt.ylabel('Employee Salary')
# plt.show()

# 2.Create a scatter plot of "healthy eating"and "active_lifestyle" features

# plt.figure(figsize= (10,5))
# sns.scatterplot(data=data, x = 'healthy_eating', y = 'active_lifestyle', color ='red',edgecolor ='green', alpha = 0.5)
# plt.title("Scatterplot of healthy eating v/s active lifestyle ")
# plt.xlabel('healthy eating')
# plt.ylabel('active lifestyle')
# plt.show()

# 3.Create a scatter plot of "healthy eating"and "Salary" features

# plt.figure(figsize= (10,5))
# sns.scatterplot(data=data, x = 'healthy_eating', y = 'salary', color ='k',edgecolor ='green', alpha = 0.5)
# plt.title("Scatterplot of healthy eating v/s salary")
# plt.xlabel('healthy eating')
# plt.ylabel('salary')
# plt.show()

# 4.create a count plot of the "groups" feature
# plt.figure(figsize=(10,5))
# sns.countplot(data =data, x= 'groups', edgecolor = 'grey', alpha = 0.7)
# plt.title("count plot of groups")
# plt.xlabel("groups")
# plt.ylabel("count")
# plt.show()

# 5.Create a Histogram of the "Salary" features

# plt.figure(figsize = (11,6))

# sns.histplot(data=data, x = "salary", color="orange", edgecolor= "grey", alpha= 0.7, bins=10)

# plt.title("histogram of salary")
# plt.xlabel("salary")
# plt.ylabel("count")
# plt.show()

# PART 3 Analysis of data

# Employee healthy_eating is greater than 8
# sub1= data[data['healthy_eating']>8]
# sub1

# Employee Salary less than 1000

# sub2= data[data['salary']<1000]
# sub2

# Employee healthy_eating is greater than 8 and Salary less than 1000

# sub3= data[(data['healthy_eating']>8) & (data['salary']<1000)]
# sub3